# Generated by Django 3.2.15 on 2022-08-18 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoughRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ingredient_dough', models.BooleanField(blank=True, null=True)),
                ('ingredient_sauce', models.BooleanField(blank=True, null=True)),
                ('ingredient_pizza', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IngredientDough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('dough', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdrs.doughrecipe')),
                ('ingredient', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='pdrs.ingredient')),
            ],
        ),
    ]
