# Generated by Django 3.2.15 on 2022-08-18 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdrs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='ingredient_dough',
            new_name='dough',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='ingredient_pizza',
            new_name='pizza',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='ingredient_sauce',
            new_name='sauce',
        ),
    ]
