# Generated by Django 3.2.15 on 2022-08-18 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdrs', '0002_auto_20220818_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='dough',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='pizza',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='sauce',
            field=models.BooleanField(null=True),
        ),
    ]
