# Generated by Django 3.2.15 on 2022-08-31 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdrs', '0003_auto_20220818_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='dough',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='pizza',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='sauce',
            field=models.BooleanField(),
        ),
    ]
