# Generated by Django 3.2.15 on 2022-09-01 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdrs', '0004_auto_20220831_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Pizza', 'Pizza'), ('Sauce', 'Sauce'), ('Dough', 'Dough')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('ingredient', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='pdrs.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdrs.recipe')),
            ],
        ),
        migrations.RemoveField(
            model_name='ingredientdough',
            name='dough',
        ),
        migrations.RemoveField(
            model_name='ingredientdough',
            name='ingredient',
        ),
        migrations.DeleteModel(
            name='DoughRecipe',
        ),
        migrations.DeleteModel(
            name='IngredientDough',
        ),
    ]
